/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.jmeter.plugins.copilot;

import java.awt.BorderLayout;

import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.JComponent;
import javax.swing.JPanel;

import org.apache.jmeter.plugins.copilot.gui.CopilotChatPanel;
import org.apache.jmeter.samplers.SampleResult;
import org.apache.jmeter.testelement.TestElement;
import org.apache.jmeter.visualizers.gui.AbstractVisualizer;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.google.auto.service.AutoService;

/**
 * JMeter Visualizer plugin that provides a GitHub Copilot Chat interface
 * for generating JMeter test plans through natural language conversation.
 * 
 * This plugin allows users to describe the tests they want to create, and
 * Copilot will generate the appropriate JMeter elements and add them to
 * the test plan.
 */
@AutoService(org.apache.jmeter.gui.JMeterGUIComponent.class)
public class CopilotChatVisualizer extends AbstractVisualizer {

    private static final long serialVersionUID = 1L;
    private static final Logger log = LoggerFactory.getLogger(CopilotChatVisualizer.class);

    private CopilotChatPanel chatPanel;
    private JPanel mainPanel;

    /**
     * Creates a new CopilotChatVisualizer instance.
     */
    public CopilotChatVisualizer() {
        super();
        log.info("Initializing Copilot Chat Visualizer");
        init();
    }

    /**
     * Initialize the GUI components.
     */
    private void init() {
        setLayout(new BorderLayout());
        setBorder(makeBorder());

        // Create the main panel with vertical box layout
        Box box = Box.createVerticalBox();
        box.add(makeTitlePanel());

        // Create the chat panel
        chatPanel = new CopilotChatPanel(this::onTestPlanGenerated);

        // Create wrapper panel for the chat
        mainPanel = new JPanel(new BorderLayout());
        mainPanel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        mainPanel.add(chatPanel, BorderLayout.CENTER);

        add(box, BorderLayout.NORTH);
        add(mainPanel, BorderLayout.CENTER);
    }

    /**
     * Callback method invoked when a test plan is generated by Copilot.
     * This method integrates the generated test elements into the JMeter GUI.
     *
     * @param testPlanXml The generated test plan in JMeter XML format
     */
    private void onTestPlanGenerated(String testPlanXml) {
        log.info("Test plan generated by Copilot");
        // This will be implemented to integrate with JMeter's GUI
        // to add the generated elements to the test plan tree
        try {
            JMeterTestPlanIntegrator.integrateTestPlan(testPlanXml);
        } catch (Exception e) {
            log.error("Failed to integrate generated test plan", e);
            chatPanel.displayError("Failed to add test to plan: " + e.getMessage());
        }
    }

    @Override
    public String getLabelResource() {
        return "copilot_chat_title";
    }

    @Override
    public String getStaticLabel() {
        return "Copilot Chat";
    }

    @Override
    public void add(SampleResult sample) {
        // This visualizer doesn't process sample results
        // It's used for test generation, not result visualization
    }

    @Override
    public void clearData() {
        // Clear the chat history if needed
        if (chatPanel != null) {
            chatPanel.clearChat();
        }
    }

    @Override
    public TestElement makeTestElement() {
        CopilotChatTestElement element = new CopilotChatTestElement();
        modifyTestElement(element);
        return element;
    }

    @Override
    public void modifyTestElement(TestElement element) {
        super.modifyTestElement(element);
        if (element instanceof CopilotChatTestElement copilotElement) {
            // Save any configuration from the GUI to the test element
            copilotElement.setModel(chatPanel.getSelectedModel());
        }
    }

    @Override
    public void configure(TestElement element) {
        super.configure(element);
        if (element instanceof CopilotChatTestElement copilotElement) {
            // Load configuration from the test element to the GUI
            chatPanel.setSelectedModel(copilotElement.getModel());
        }
    }

    @Override
    public JComponent getPrintableComponent() {
        return mainPanel;
    }

    /**
     * Clean up resources when the visualizer is being disposed.
     */
    public void dispose() {
        if (chatPanel != null) {
            chatPanel.shutdown();
        }
    }
}
